name: reviwer
on:
  pull_request:
    types:
      - edited
      - review-requested

env:
  GITHUB_TOKEN: ${{ secrets.TEAM_READ_TOKEN }}

jobs:
  reviewer:
    runs-on: ubuntu-latest
    env:
      pullnumber: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 
        run: |
          org="mrngshtorg"
          repo="mrngshttest"
          team="all"
          teamslug="${org}/${team}"
          echo $teamslug
          gh pr view "${pullnumber}" 
          gh api -X GET "/orgs/$org/teams/$team/members" | jq -c '[.[].login | select(. != "${{ github.actor }}")]'
          reviewreq=$(gh pr view "${pullnumber}" --json reviewRequests | jq -r '.reviewRequests[].slug')
          echo $reviewreq
          if gh pr view "${pullnumber}" --json reviewRequests | jq -r '.reviewRequests[].slug' | grep $teamslug; then
            members=$(gh api -X GET "/orgs/$org/teams/$team/members" | jq -c '[.[].login | select(. != "${{ github.actor }}")]')
            gh api -X POST "/repos/${org}/${repo}/pulls/${pullnumber}/requested_reviewers"-f reviewers[]="${members}"
          fi 
